version: '3.9'

volumes:
  node_modules: {}
  redis_data: {}

services:
  app:
    image: pm4-node
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm4_node
    ports:
      - '3000:3000'
    env_file:
      - ./compose/envs/app.env
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    depends_on:
      - redis
    tty: true

  redis:
    image: redis/redis-stack:latest
    container_name: pm4_redis
    env_file:
      - ./compose/envs/redis.env
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - redis_data:/data
    restart: unless-stopped
